name: Deploy to Salesforce

on:
  push:
    branches:
      - main
  workflow_dispatch: # Enables manual execution

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Step 2: Install Node.js and npm (required for Salesforce CLI)
      - name: Install Node.js and npm
        run: |
          sudo apt update
          sudo apt install -y nodejs npm
          node -v
          npm -v

      # Step 3: Install Salesforce CLI
      - name: Install Salesforce CLI
        run: |
          npm install --global @salesforce/cli
          sf --version

      # Step 4: Install the sfdx-git-delta (SGD) Plugin for metadata deployment
      - name: Install sfdx-git-delta (SGD) Plugin
        run: |
          echo Y | sf plugins:install sfdx-git-delta
          sf plugins

      # Step 5: Authenticate with Salesforce using JWT authentication
      - name: Authenticate with JWT
        run: |
          echo "${{ secrets.JWT_SERVER_KEY }}" > server.key
          sf org login jwt \
            --instance-url ${{ vars.INSTANCE_URL }} \
            --client-id ${{ secrets.CONSUMER_KEY }} \
            --username ${{ secrets.DEPLOYMENT_USER_NAME }} \
            --jwt-key-file server.key

      # Step 6: Run Apex tests before deployment
      - name: Run Apex Tests
        run: |
          sf apex run test --target-org ${{ secrets.DEPLOYMENT_USER_NAME }} --result-format human

      # Step 7: Generate metadata delta changes and deploy to Salesforce
      - name: Deploy to Salesforce using sfdx-git-delta
        run: |
          mkdir changed-mdapi
          sfdx sgd:source:delta \
            --to HEAD \
            --from $(git rev-parse HEAD~1) \
            --output changed-mdapi
          sf project deploy start --metadata-dir changed-mdapi --target-org ${{ secrets.DEPLOYMENT_USER_NAME }}

      # Step 8: Logout from Salesforce after deployment
      - name: Post Deployment Cleanup
        run: |
          sf org logout --no-prompt

      # Step 9: Print a success message
      - name: Deployment Success
        run: echo "Deployment completed successfully!"
