name: Deploy to Salesforce

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Checkout the latest code from the repository
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Install Node.js and npm for running Salesforce CLI
      - name: Install Node.js and npm
        run: |
          sudo apt update
          sudo apt install -y nodejs npm
          node -v
          npm -v

      # Install Salesforce CLI globally
      - name: Install Salesforce CLI
        run: |
          npm install --global @salesforce/cli
          sf --version

      # Install the sfdx-git-delta (SGD) plugin to deploy only changed metadata
      - name: Install sfdx-git-delta (SGD) Plugin
        run: |
          echo Y | sf plugins:install sfdx-git-delta
          sf plugins

      # Authenticate to Salesforce using JWT-based authentication
      - name: Authenticate with JWT
        run: |
          sf org login jwt \
            --instance-url ${{ secrets.INSTANCE_URL }} \
            --client-id ${{ secrets.CONSUMER_KEY }} \
            --username ${{ secrets.DEPLOYMENT_USER_NAME }} \
            --jwt-key-file <(echo "${{ secrets.JWT_SERVER_KEY }}" | base64 --decode)

      # Identify and deploy only changed metadata using sfdx-git-delta
      - name: Deploy to Salesforce using sfdx-git-delta
        run: |
          mkdir changed-mdapi
          sfdx sgd:source:delta \
            --to HEAD \
            --from $(git rev-parse HEAD~1) \
            --output changed-mdapi
          sf project deploy start --metadata-dir changed-mdapi --target-org ${{ secrets.DEPLOYMENT_USER_NAME }}

      # Logout from Salesforce to free up session space
      - name: Post Deployment Cleanup
        run: |
          sf org logout --no-prompt

      # Print a success message upon successful deployment
      - name: Deployment Success
        run: echo "Deployment completed successfully!"
